minimumReleaseAge: 10080 # 7 days

minimumReleaseAgeExclude:
  - 'oxc-transform-react'
  - '@oxc-transform-react/*'
  - '@vitejs/plugin-react'

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
    - arm64
